version: "3"
services:
  db-mysql:
    container_name: juchelin-guide-db
    restart: unless-stopped
    build:
      context: serverSides/docker/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234!
      - MYSQL_DATABASE=juchelin-guide
  node-app:
    container_name: juchelin-guide-app
    restart: unless-stopped
    depends_on:
      - db-mysql
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - "3000:3000"
