version: "3"
services:
  db-mysql:
    container_name: juchelin-guide-db
    restart: unless-stopped
    build:
      context: serverSides/docker/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234!
      - MYSQL_DATABASE=juchelin-guide
  node-app:
    container_name: juchelin-guide-app
    restart: unless-stopped
    # Next.js 에서 hot reloading 을 위한 볼륨 지정
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    depends_on:
      - db-mysql
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - "3000:3000"
