version: "3"
services:
  db:
    container_name: juchelin-guide-db
    restart: unless-stopped
    platform: linux/amd64
    build:
      context: serverSides/docker/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234!
      - MYSQL_DATABASE=juchelin-guide
  app:
    container_name: juchelin-guide-app
    restart: unless-stopped
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    depends_on:
      - db
    platform: linux/amd64
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - "3000:3000"
